### ISSUE TITLE
DAY 0 Set up the project - group task & Kanban

### ISSUE THREAD

**Issue by leonardoeng13** [leonardoeng13/Capstone-Ruby#11]
### Project requirements

- Join a Zoom call with your team. Only one person needs to copy the board on behalf of the entire team but everybody should help during the call.
- Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] Ruby Group Capstone Project](https://github.com/microverseinc/curriculum-ruby/projects/1) board.
- Open the GitHub project (Kanban board) in your team repo.
- Open [project requirements](./catalog_of_my_things.md) and read them carefully.
- Open [project requirements divided by team member](/.catalog_of_my_things_divided.md) and compare it with the [project requirements](./catalog_of_my_things.md).
- Create tasks on your Kanban board based on the [project requirements divided by team member](/.catalog_of_my_things_divided.md).
- Each task should be a separate card that:
    - Has a descriptive title.
    - Has the number of points in the `[Xpt]` prefix. That number should indicate the number of `points` that show how complex the task is. **1 point = 1 hour of estimated work**. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
    - Has a description of the task.
- Each of the team members should assign themselves to the cards as divided in the [project requirements divided by team member](./catalog_of_my_things_divided.md) (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.
- [Project Issues](https://github.com/leonardoeng13/Capstone-Ruby/projects/1)

**Comment by mikenath223** [comment]
Hello there  

Your project is complete!  There is nothing else to say. 🛳 
Congratulations! 🎉 

Happy coding. Cheers! 🚀🚀

If you feel something isn't clear enough you can leave a question or comment in the issue thread.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
